# Generated by Django 4.0.2 on 2022-02-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('referral', models.CharField(max_length=10)),
                ('last_modified', models.DateField()),
                ('is_strangel', models.BooleanField(default=0)),
                ('image', models.ImageField(upload_to='./user_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
