# Generated by Django 4.0.2 on 2022-02-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Safepoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_name', models.CharField(max_length=100)),
                ('sp_address', models.TextField()),
                ('sp_number', models.CharField(max_length=20)),
                ('sp_latitude', models.CharField(max_length=50)),
                ('sp_longitude', models.CharField(max_length=50)),
                ('sp_timings', models.TextField()),
                ('sp_created_at', models.DateField(auto_now=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('sp_image', models.ImageField(upload_to='./sp_images/')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
